# Use the official Node.js LTS (Long Term Support) image as the base image
FROM node:18 AS build

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the container
COPY . .

# Build the Next.js application for production
RUN npm run build



# Set the working directory inside the container
WORKDIR /app

# Copy the built files from the "build" stage of the previous image
COPY --from=build /app/.next ./.next
COPY --from=build /app/public ./public
COPY --from=build /app/package.json ./package.json

# Install only production dependencies (omit devDependencies)
RUN npm install --only=production

# Expose the port that Next.js uses (default is 3000)
EXPOSE 3000

# Start the Next.js application
CMD ["npm", "start"]
